### ISSUE TITLE
ImportError: cannot import name 'mulaw' from 'wavenet_vocoder.util'

### ISSUE THREAD

**Issue by c1a1o1** [wqt2019/tacotron-2_melgan#7]
2020-11-28 13:37:48.767616: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cudart64_101.dll
Traceback (most recent call last):
  File "F:/work/tacotron-2_melgan-master/preprocess.py", line 5, in <module>
    from datasets import preprocessor
  File "F:\work\tacotron-2_melgan-master\datasets\preprocessor.py", line 7, in <module>
    from wavenet_vocoder.util import is_mulaw, is_mulaw_quantize, mulaw, mulaw_quantize
ImportError: cannot import name 'mulaw' from 'wavenet_vocoder.util' (F:\ProgramData\Anaconda3\lib\site-packages\wavenet_vocoder\util.py)

**Comment by wqt2019** [comment]
https://github.com/wqt2019/tacotron-2_wavernn/blob/master/wavenet_vocoder/util.py

**Comment by c1a1o1** [comment]
thank s a lot
